// Code generated by golex. DO NOT EDIT.

package parser

import (
	"bufio"
	"go/token"
	"io"
	"unicode"

	"modernc.org/golex/lex"
)

// Allocate Character classes anywhere in [0x80, 0xFF].
const (
	classUnicodeLeter = iota + 0x80
	classUnicodeDigit
	classOther
)

type lexer struct {
	*lex.Lexer
}

func rune2Class(r rune) int {
	if r >= 0 && r < 0x80 { // Keep ASCII as it is.
		return int(r)
	}
	if unicode.IsLetter(r) {
		return classUnicodeLeter
	}
	if unicode.IsDigit(r) {
		return classUnicodeDigit
	}
	return classOther
}

func newLexer(src io.Reader, dst io.Writer, fName string) *lexer {
	file := token.NewFileSet().AddFile(fName, -1, 1<<31-1)
	lx, err := lex.New(file, bufio.NewReader(src), lex.RuneClass(rune2Class))
	if err != nil {
		panic(err)
	}
	return &lexer{lx}
}

func (l *lexer) Lex(lval *yySymType) int {
	c := l.Enter()

yystate0:
	yyrule := -1
	_ = yyrule
	c = l.Rule0()

	goto yystart1

	goto yystate0 // silence unused label error
	goto yyAction // silence unused label error
yyAction:
	switch yyrule {
	case 1:
		goto yyrule1
	case 2:
		goto yyrule2
	case 3:
		goto yyrule3
	case 4:
		goto yyrule4
	case 5:
		goto yyrule5
	case 6:
		goto yyrule6
	case 7:
		goto yyrule7
	case 8:
		goto yyrule8
	case 9:
		goto yyrule9
	case 10:
		goto yyrule10
	case 11:
		goto yyrule11
	case 12:
		goto yyrule12
	case 13:
		goto yyrule13
	case 14:
		goto yyrule14
	case 15:
		goto yyrule15
	case 16:
		goto yyrule16
	case 17:
		goto yyrule17
	case 18:
		goto yyrule18
	case 19:
		goto yyrule19
	case 20:
		goto yyrule20
	case 21:
		goto yyrule21
	case 22:
		goto yyrule22
	case 23:
		goto yyrule23
	case 24:
		goto yyrule24
	case 25:
		goto yyrule25
	case 26:
		goto yyrule26
	case 27:
		goto yyrule27
	case 28:
		goto yyrule28
	case 29:
		goto yyrule29
	}
	goto yystate1 // silence unused label error
yystate1:
	c = l.Next()
yystart1:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate3
	case c == '-':
		goto yystate4
	case c == '/':
		goto yystate7
	case c == 'A' || c == 'a':
		goto yystate8
	case c == 'B' || c == 'C' || c == 'G' || c >= 'I' && c <= 'L' || c == 'O' || c == 'Q' || c >= 'V' && c <= 'Z' || c == '_' || c == 'b' || c == 'c' || c == 'g' || c >= 'i' && c <= 'l' || c == 'o' || c == 'q' || c >= 'v' && c <= 'z' || c == '\u0080':
		goto yystate25
	case c == 'D' || c == 'd':
		goto yystate26
	case c == 'E' || c == 'e':
		goto yystate32
	case c == 'F' || c == 'f':
		goto yystate36
	case c == 'H' || c == 'h':
		goto yystate43
	case c == 'M' || c == 'm':
		goto yystate49
	case c == 'N' || c == 'n':
		goto yystate59
	case c == 'P' || c == 'p':
		goto yystate63
	case c == 'R' || c == 'r':
		goto yystate70
	case c == 'S' || c == 's':
		goto yystate83
	case c == 'T' || c == 't':
		goto yystate87
	case c == 'U' || c == 'u':
		goto yystate91
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate2
	case c == '\u0081':
		goto yystate100
	case c >= '0' && c <= '9':
		goto yystate5
	}

yystate2:
	c = l.Next()
	yyrule = 1
	l.Mark()
	switch {
	default:
		goto yyrule1
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate2
	}

yystate3:
	c = l.Next()
	yyrule = 29
	l.Mark()
	goto yyrule29

yystate4:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == '>':
		goto yystate6
	case c >= '0' && c <= '9':
		goto yystate5
	}

yystate5:
	c = l.Next()
	yyrule = 25
	l.Mark()
	switch {
	default:
		goto yyrule25
	case c >= '0' && c <= '9':
		goto yystate5
	}

yystate6:
	c = l.Next()
	yyrule = 24
	l.Mark()
	goto yyrule24

yystate7:
	c = l.Next()
	yyrule = 28
	l.Mark()
	switch {
	default:
		goto yyrule28
	case c == ' ' || c >= '.' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate7
	}

yystate8:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'D' || c == 'd':
		goto yystate19
	case c == 'R' || c == 'r':
		goto yystate21
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Q' || c >= 'S' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate9:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate10
	}

yystate10:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate11:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'D' || c == 'd':
		goto yystate12
	case c == 'M' || c == 'm':
		goto yystate15
	}

yystate12:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'S' || c == 's':
		goto yystate13
	}

yystate13:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'K' || c == 'k':
		goto yystate14
	}

yystate14:
	c = l.Next()
	yyrule = 26
	l.Mark()
	goto yyrule26

yystate15:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'I' || c == 'i':
		goto yystate16
	}

yystate16:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'A' || c == 'a':
		goto yystate17
	}

yystate17:
	c = l.Next()
	yyrule = 27
	l.Mark()
	goto yyrule27

yystate18:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'D' || c == 'd':
		goto yystate12
	}

yystate19:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'D' || c == 'd':
		goto yystate20
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate20:
	c = l.Next()
	yyrule = 4
	l.Mark()
	switch {
	default:
		goto yyrule4
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate21:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'R' || c == 'r':
		goto yystate22
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Q' || c >= 'S' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate22:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'O' || c == 'o':
		goto yystate23
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate23:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'W' || c == 'w':
		goto yystate24
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'V' || c >= 'X' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'v' || c >= 'x' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate24:
	c = l.Next()
	yyrule = 13
	l.Mark()
	switch {
	default:
		goto yyrule13
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate25:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate26:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'E' || c == 'e':
		goto yystate27
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate27:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'L' || c == 'l':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'K' || c >= 'M' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate28:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'E' || c == 'e':
		goto yystate29
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate29:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'T' || c == 't':
		goto yystate30
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate30:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'E' || c == 'e':
		goto yystate31
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate31:
	c = l.Next()
	yyrule = 17
	l.Mark()
	switch {
	default:
		goto yyrule17
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate32:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'X' || c == 'x':
		goto yystate33
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'W' || c == 'Y' || c == 'Z' || c == '_' || c >= 'a' && c <= 'w' || c == 'y' || c == 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate33:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'E' || c == 'e':
		goto yystate34
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate34:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'C' || c == 'c':
		goto yystate35
	case c >= '0' && c <= '9' || c == 'A' || c == 'B' || c >= 'D' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate35:
	c = l.Next()
	yyrule = 7
	l.Mark()
	switch {
	default:
		goto yyrule7
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate36:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'D' || c == 'd':
		goto yystate37
	case c == 'I' || c == 'i':
		goto yystate41
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate37:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'I' || c == 'i':
		goto yystate38
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate38:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'S' || c == 's':
		goto yystate39
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate39:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'K' || c == 'k':
		goto yystate40
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'J' || c >= 'L' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate40:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate41:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'T' || c == 't':
		goto yystate42
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate42:
	c = l.Next()
	yyrule = 19
	l.Mark()
	switch {
	default:
		goto yyrule19
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate43:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'Y' || c == 'y':
		goto yystate44
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'X' || c == 'Z' || c == '_' || c >= 'a' && c <= 'x' || c == 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate44:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'P' || c == 'p':
		goto yystate45
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'O' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate45:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'H' || c == 'h':
		goto yystate46
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'G' || c >= 'I' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate46:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'E' || c == 'e':
		goto yystate47
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate47:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'N' || c == 'n':
		goto yystate48
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'M' || c >= 'O' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate48:
	c = l.Next()
	yyrule = 12
	l.Mark()
	switch {
	default:
		goto yyrule12
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate49:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'K' || c == 'k':
		goto yystate50
	case c == 'O' || c == 'o':
		goto yystate55
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'J' || c >= 'L' && c <= 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate50:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'D' || c == 'd':
		goto yystate51
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate51:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'I' || c == 'i':
		goto yystate52
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate52:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'S' || c == 's':
		goto yystate53
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate53:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'K' || c == 'k':
		goto yystate54
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'J' || c >= 'L' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate54:
	c = l.Next()
	yyrule = 16
	l.Mark()
	switch {
	default:
		goto yyrule16
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate55:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'U' || c == 'u':
		goto yystate56
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'T' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate56:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'N' || c == 'n':
		goto yystate57
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'M' || c >= 'O' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate57:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'T' || c == 't':
		goto yystate58
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate58:
	c = l.Next()
	yyrule = 10
	l.Mark()
	switch {
	default:
		goto yyrule10
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate59:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'A' || c == 'a':
		goto yystate60
	case c >= '0' && c <= '9' || c >= 'B' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate60:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'M' || c == 'm':
		goto yystate61
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'L' || c >= 'N' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'l' || c >= 'n' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate61:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'E' || c == 'e':
		goto yystate62
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate62:
	c = l.Next()
	yyrule = 14
	l.Mark()
	switch {
	default:
		goto yyrule14
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate63:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'A' || c == 'a':
		goto yystate64
	case c >= '0' && c <= '9' || c >= 'B' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate64:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'T' || c == 't':
		goto yystate65
	case c == 'U' || c == 'u':
		goto yystate67
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate65:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'H' || c == 'h':
		goto yystate66
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'G' || c >= 'I' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate66:
	c = l.Next()
	yyrule = 8
	l.Mark()
	switch {
	default:
		goto yyrule8
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate67:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'S' || c == 's':
		goto yystate68
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate68:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'E' || c == 'e':
		goto yystate69
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate69:
	c = l.Next()
	yyrule = 6
	l.Mark()
	switch {
	default:
		goto yyrule6
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate70:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'E' || c == 'e':
		goto yystate71
	case c == 'M' || c == 'm':
		goto yystate75
	case c == 'U' || c == 'u':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'L' || c >= 'N' && c <= 'T' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'l' || c >= 'n' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate71:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'A' || c == 'a':
		goto yystate72
	case c == 'P' || c == 'p':
		goto yystate74
	case c >= '0' && c <= '9' || c >= 'B' && c <= 'O' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate72:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'D' || c == 'd':
		goto yystate73
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate73:
	c = l.Next()
	yyrule = 2
	l.Mark()
	switch {
	default:
		goto yyrule2
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate74:
	c = l.Next()
	yyrule = 20
	l.Mark()
	switch {
	default:
		goto yyrule20
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate75:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'D' || c == 'd':
		goto yystate76
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate76:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'I' || c == 'i':
		goto yystate77
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate77:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'S' || c == 's':
		goto yystate78
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate78:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'K' || c == 'k':
		goto yystate79
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'J' || c >= 'L' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate79:
	c = l.Next()
	yyrule = 18
	l.Mark()
	switch {
	default:
		goto yyrule18
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate80:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'T' || c == 't':
		goto yystate81
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate81:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'A' || c == 'a':
		goto yystate82
	case c >= '0' && c <= '9' || c >= 'B' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate82:
	c = l.Next()
	yyrule = 9
	l.Mark()
	switch {
	default:
		goto yyrule9
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate83:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'I' || c == 'i':
		goto yystate84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate84:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'Z' || c == 'z':
		goto yystate85
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Y' || c == '_' || c >= 'a' && c <= 'y' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate85:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'E' || c == 'e':
		goto yystate86
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate86:
	c = l.Next()
	yyrule = 15
	l.Mark()
	switch {
	default:
		goto yyrule15
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate87:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'Y' || c == 'y':
		goto yystate88
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'X' || c == 'Z' || c == '_' || c >= 'a' && c <= 'x' || c == 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate88:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'P' || c == 'p':
		goto yystate89
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'O' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate89:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'E' || c == 'e':
		goto yystate90
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate90:
	c = l.Next()
	yyrule = 5
	l.Mark()
	switch {
	default:
		goto yyrule5
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate91:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate18
	case c == 'N' || c == 'n':
		goto yystate92
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'M' || c >= 'O' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate92:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'I' || c == 'i':
		goto yystate93
	case c == 'M' || c == 'm':
		goto yystate95
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'L' || c >= 'N' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'l' || c >= 'n' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate93:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'T' || c == 't':
		goto yystate94
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate94:
	c = l.Next()
	yyrule = 3
	l.Mark()
	switch {
	default:
		goto yyrule3
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate95:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'O' || c == 'o':
		goto yystate96
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate96:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'U' || c == 'u':
		goto yystate97
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'T' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate97:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'N' || c == 'n':
		goto yystate98
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'M' || c >= 'O' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate98:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c == 'T' || c == 't':
		goto yystate99
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate99:
	c = l.Next()
	yyrule = 11
	l.Mark()
	switch {
	default:
		goto yyrule11
	case c == '-':
		goto yystate9
	case c == '.':
		goto yystate11
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate10
	}

yystate100:
	c = l.Next()
	yyrule = 25
	l.Mark()
	switch {
	default:
		goto yyrule25
	case c == '\u0081':
		goto yystate100
	}

yyrule1: // [ \t\r\n]+

	goto yystate0
yyrule2: // read
	{
		lval.token = string(l.TokenBytes(nil))
		return read
		goto yystate0
	}
yyrule3: // unit
	{
		lval.token = string(l.TokenBytes(nil))
		return unit
		goto yystate0
	}
yyrule4: // add
	{
		lval.token = string(l.TokenBytes(nil))
		return add
		goto yystate0
	}
yyrule5: // type
	{
		lval.token = string(l.TokenBytes(nil))
		return tpe
		goto yystate0
	}
yyrule6: // pause
	{
		lval.token = string(l.TokenBytes(nil))
		return pause
		goto yystate0
	}
yyrule7: // exec
	{
		lval.token = string(l.TokenBytes(nil))
		return exec
		goto yystate0
	}
yyrule8: // path
	{
		lval.token = string(l.TokenBytes(nil))
		return path
		goto yystate0
	}
yyrule9: // ruta
	{
		lval.token = string(l.TokenBytes(nil))
		return ruta
		goto yystate0
	}
yyrule10: // mount
	{
		lval.token = string(l.TokenBytes(nil))
		return mount
		goto yystate0
	}
yyrule11: // unmount
	{
		lval.token = string(l.TokenBytes(nil))
		return unmount
		goto yystate0
	}
yyrule12: // hyphen
	{
		lval.token = string(l.TokenBytes(nil))
		return hyphen
		goto yystate0
	}
yyrule13: // arrow
	{
		lval.token = string(l.TokenBytes(nil))
		return arrow
		goto yystate0
	}
yyrule14: // name
	{
		lval.token = string(l.TokenBytes(nil))
		return name
		goto yystate0
	}
yyrule15: // size
	{
		lval.token = string(l.TokenBytes(nil))
		return size
		goto yystate0
	}
yyrule16: // mkdisk
	{
		lval.token = string(l.TokenBytes(nil))
		return mkdisk
		goto yystate0
	}
yyrule17: // delete
	{
		lval.token = string(l.TokenBytes(nil))
		return delete
		goto yystate0
	}
yyrule18: // rmdisk
	{
		lval.token = string(l.TokenBytes(nil))
		return rmdisk
		goto yystate0
	}
yyrule19: // fit
	{
		lval.token = string(l.TokenBytes(nil))
		return fit
		goto yystate0
	}
yyrule20: // rep
	{
		lval.token = string(l.TokenBytes(nil))
		return rep
		goto yystate0
	}
yyrule21: // fdisk
	{
		lval.token = string(l.TokenBytes(nil))
		return fdisk
		goto yystate0
	}
yyrule22: // {id}
	{
		lval.token = string(l.TokenBytes(nil))
		return id
		goto yystate0
	}
yyrule23: // {hyphen}
	{
		lval.token = string(l.TokenBytes(nil))
		return hyphen
		goto yystate0
	}
yyrule24: // {arrow}
	{
		lval.token = string(l.TokenBytes(nil))
		return arrow
		goto yystate0
	}
yyrule25: // {digit}
	{
		lval.token = string(l.TokenBytes(nil))
		return digit
		goto yystate0
	}
yyrule26: // {diskName}
	{
		lval.token = string(l.TokenBytes(nil))
		return diskName
		goto yystate0
	}
yyrule27: // {mia_file}
	{
		lval.token = string(l.TokenBytes(nil))
		return mia_file
		goto yystate0
	}
yyrule28: // {route}
	{
		lval.token = string(l.TokenBytes(nil))
		return route
		goto yystate0
	}
yyrule29: // {quote}
	{
		lval.token = string(l.TokenBytes(nil))
		return quote
		goto yystate0
	}
	panic("unreachable")

	goto yyabort // silence unused label error

yyabort: // no lexem recognized
	if c, ok := l.Abort(); ok {
		return int(c)
	}
	goto yyAction
}
