// Code generated by goyacc par.y. DO NOT EDIT.

//line par.y:2
package parser

import __yyfmt__ "fmt"

//line par.y:2

import (
	"MIA-P1/actions"
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"
)

var newDisk actions.Disk = actions.Disk{}
var newPartition actions.Partition = actions.Partition{}
var newFDisk actions.FDISK = actions.FDISK{}
var newMount actions.Mount = actions.Mount{}
var newUnmount actions.Unmount = actions.Unmount{}
var newRep actions.Rep = actions.Rep{}
var stringAux string = ""
var skipFound bool = false

type node struct {
	name     string
	children []node
}

func (n node) String() string {
	buf := new(bytes.Buffer)
	n.print(buf, " ")
	return buf.String()
}

func (n node) print(out io.Writer, indent string) {
	fmt.Fprintf(out, "\n%v%v", indent, n.name)
	for _, nn := range n.children {
		nn.print(out, indent+"  ")
	}
}

func Node(name string) node           { return node{name: name} }
func (n node) append(nn ...node) node { n.children = append(n.children, nn...); return n }

//line par.y:47
type yySymType struct {
	yys   int
	node  node
	token string
}

const arrow = 57346
const add = 57347
const delete = 57348
const digit = 57349
const digits = 57350
const diskName = 57351
const equals = 57352
const exec = 57353
const fit = 57354
const fdisk = 57355
const greater = 57356
const hyphen = 57357
const idn = 57358
const id = 57359
const less = 57360
const mia_file = 57361
const mount = 57362
const mount_name = 57363
const mbr = 57364
const mkfs = 57365
const mkdisk = 57366
const number = 57367
const negNumber = 57368
const name = 57369
const path = 57370
const pause = 57371
const rmdisk = 57372
const size = 57373
const tpe = 57374
const unit = 57375
const unmount = 57376
const rep = 57377
const read = 57378
const route = 57379
const ruta = 57380
const quote = 57381

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"arrow",
	"add",
	"delete",
	"digit",
	"digits",
	"diskName",
	"equals",
	"exec",
	"fit",
	"fdisk",
	"greater",
	"hyphen",
	"idn",
	"id",
	"less",
	"mia_file",
	"mount",
	"mount_name",
	"mbr",
	"mkfs",
	"mkdisk",
	"number",
	"negNumber",
	"name",
	"path",
	"pause",
	"rmdisk",
	"size",
	"tpe",
	"unit",
	"unmount",
	"rep",
	"read",
	"route",
	"ruta",
	"quote",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line par.y:269

// Run exported
func Run() {
	fi := bufio.NewReader(os.NewFile(0, "stdin"))
	yyDebug = 0
	yyErrorVerbose = true
	for {
		var eqn string
		var ok bool

		fmt.Printf(">> ")
		if eqn, ok = input(fi); ok {
			l := newLexer(bytes.NewBufferString(eqn), os.Stdout, "file.name")
			yyParse(l)
		} else {
			break
		}
	}

}

// RunExec exported
func RunExec(reader *bufio.Reader) {
	yyDebug = 0
	yyErrorVerbose = true
	var stringAux string = ""

	for {
		var ok bool
		var eqn string

		if eqn, ok = input(reader); ok {
			eqn = strings.TrimSpace(eqn)
			eqn = strings.Replace(eqn, " ", "", -1)
			if strings.HasPrefix(eqn, "#") {
				continue
			}
			if len(eqn) == 0 || len(eqn) == 1 {
				continue
			}
			if skipFound == true {
				stringAux = stringAux + eqn
				stringAux = strings.Replace(stringAux, " ", "", -1)
				fmt.Println(">>", stringAux)
				l := newLexer(bytes.NewBufferString(stringAux), os.Stdout, "file.name")
				stringAux = ""
				skipFound = false
				yyParse(l)
				continue
			}
			if strings.HasSuffix(eqn, "\\*") {
				stringAux = eqn
				stringAux = strings.TrimRight(stringAux, "\\*")
				skipFound = true
				continue
			}
			fmt.Println(">>", eqn)
			l := newLexer(bytes.NewBufferString(eqn), os.Stdout, "file.name")
			yyParse(l)

		} else {
			break
		}
	}
}

func Exec(route string) {
	re, _ := regexp.Compile(`[a-zA-Z]([a-zA-Z]|[0-9])*\.mia`)
	diskName := re.FindString(route)
	if len(diskName) == 0 {
		fmt.Println(">> No file found. Try again.")
		return
	}
	file, err := os.Open(route)
	if err != nil {
		fmt.Println(">> Couldn't read file. Try again.")
		return
	}
	defer file.Close()
	reader := bufio.NewReader(file)
	RunExec(reader)
}

func input(fi *bufio.Reader) (string, bool) {
	s, err := fi.ReadString('\n')
	if err != nil {
		return "", false
	}
	return s, true
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 140

var yyAct = [...]int{
	72, 16, 42, 19, 138, 124, 68, 123, 137, 122,
	14, 121, 135, 20, 17, 134, 69, 70, 133, 21,
	18, 117, 132, 116, 15, 23, 22, 71, 104, 37,
	105, 108, 61, 60, 99, 131, 130, 128, 127, 59,
	126, 125, 102, 66, 67, 33, 53, 52, 75, 136,
	51, 78, 54, 29, 63, 64, 55, 84, 62, 58,
	57, 46, 45, 49, 26, 140, 56, 120, 94, 119,
	115, 112, 111, 110, 109, 107, 101, 100, 50, 65,
	48, 118, 47, 129, 43, 38, 34, 30, 27, 39,
	44, 35, 31, 106, 114, 113, 103, 139, 98, 97,
	96, 95, 93, 92, 91, 90, 89, 88, 87, 86,
	85, 83, 82, 81, 80, 79, 77, 76, 74, 73,
	40, 3, 28, 1, 24, 41, 13, 12, 2, 10,
	36, 9, 8, 32, 7, 6, 5, 11, 25, 4,
}

var yyPact = [...]int{
	-10, -1000, -10, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 73, 72, 77, 71, 76, 70,
	74, -1000, 116, 69, -1000, 73, -1000, 34, 72, -1000,
	63, 35, 71, -1000, 19, 28, 70, -1000, 27, 62,
	6, 69, -1000, -11, -1000, 115, 114, -1000, 113, 112,
	-1000, 111, 110, 109, 108, 107, -1000, 106, 105, 104,
	103, 102, 101, 100, 99, 98, -1000, -1000, 97, 96,
	95, 94, -1000, -5, 60, -1000, 59, 5, -1000, 89,
	-9, 84, 58, -8, -1000, 57, 56, 55, 54, 88,
	87, 53, -16, 65, -1000, 52, 50, -28, -32, 4,
	-1000, -1000, -1000, -1000, -1000, 3, -1000, -1000, 1, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 0, -1000, 68, -1000,
	-1000, -1, -1000, -2, -1000, -17, -21, -24, -27, 17,
	-31, -35, -1000, -1000, -1000, -1000, 93, -1000, -1000, 48,
	-1000,
}

var yyPgo = [...]int{
	0, 139, 138, 64, 137, 136, 135, 134, 133, 45,
	132, 131, 130, 29, 129, 121, 128, 127, 126, 125,
	2, 123, 0, 122, 53,
}

var yyR1 = [...]int{
	0, 21, 16, 16, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 4, 17, 6, 7, 8, 8,
	9, 9, 9, 9, 9, 18, 19, 19, 20, 20,
	20, 20, 20, 20, 1, 1, 2, 2, 3, 3,
	5, 23, 23, 24, 11, 12, 12, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 10, 14, 14, 22,
}

var yyR2 = [...]int{
	0, 1, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 3, 5, 2, 1, 3,
	4, 4, 4, 6, 4, 2, 1, 3, 4, 4,
	6, 4, 6, 4, 2, 1, 1, 3, 6, 4,
	2, 1, 3, 4, 2, 1, 3, 4, 4, 4,
	4, 4, 4, 4, 6, 4, 7, 5, 9, 0,
}

var yyChk = [...]int{
	-1000, -21, -16, -15, -1, -5, -6, -7, -10, -11,
	-14, -4, -17, -18, 20, 34, 11, 24, 30, 13,
	23, 29, 36, 35, -15, -2, -3, 15, -23, -24,
	15, 15, -8, -9, 15, 15, -12, -13, 15, 15,
	4, -19, -20, 15, -3, 28, 27, -24, 17, 28,
	-9, 31, 28, 27, 33, 28, -13, 33, 32, 12,
	6, 5, 31, 27, 28, 17, 37, -20, 17, 27,
	28, 38, -22, 4, 4, -22, 4, 4, -22, 4,
	4, 4, 4, 4, -22, 4, 4, 4, 4, 4,
	4, 4, 4, 4, -22, 4, 4, 4, 4, 39,
	17, 17, 37, 7, 37, 39, 9, 17, 39, 17,
	17, 17, 17, 7, 7, 17, 39, 37, 16, 17,
	17, 39, 37, 39, 37, 37, 37, 37, 37, 15,
	37, 37, 39, 39, 39, 39, 32, 39, 39, 4,
	17,
}

var yyDef = [...]int{
	0, -2, 1, 2, 4, 5, 6, 7, 8, 9,
	10, 11, 12, 13, 35, 0, 0, 0, 0, 0,
	0, 14, 0, 0, 3, 34, 36, 0, 40, 41,
	0, 0, 17, 18, 0, 0, 44, 45, 0, 0,
	0, 25, 26, 0, 59, 0, 0, 59, 0, 0,
	59, 0, 0, 0, 0, 0, 59, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 15, 59, 0, 0,
	0, 0, 37, 0, 0, 42, 0, 0, 19, 0,
	0, 0, 0, 0, 46, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 27, 0, 0, 0, 0, 0,
	39, 43, 16, 20, 21, 0, 22, 24, 0, 47,
	48, 49, 50, 51, 52, 53, 0, 55, 57, 28,
	29, 0, 31, 0, 33, 0, 0, 0, 0, 0,
	0, 0, 38, 23, 56, 54, 0, 30, 32, 0,
	58,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line par.y:173
		{
			actions.PauseAction()
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line par.y:175
		{
			actions.ReadFile(yyDollar[3].token)
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line par.y:177
		{
			Exec(yyDollar[5].token)
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line par.y:179
		{
			newDisk.CreateDisk()
			newDisk = actions.Disk{}
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:187
		{
			newDisk.SetDiskSize(yyDollar[4].token)
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:188
		{
			newDisk.SetDiskRoute(yyDollar[4].token)
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:189
		{
			newDisk.SetDiskName(yyDollar[4].token)
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
//line par.y:190
		{
			newDisk.SetDiskRoute(yyDollar[5].token)
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:191
		{
			newDisk.SetDiskUnit(yyDollar[4].token)
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line par.y:195
		{
			newRep.CreateRep()
			newRep = actions.Rep{}
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:203
		{
			newRep.SetRepID(yyDollar[4].token)
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:204
		{
			newRep.SetRepName(yyDollar[4].token)
		}
	case 30:
		yyDollar = yyS[yypt-6 : yypt+1]
//line par.y:205
		{
			newRep.SetRepPath(yyDollar[5].token)
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:206
		{
			newRep.SetRepPath(yyDollar[4].token)
		}
	case 32:
		yyDollar = yyS[yypt-6 : yypt+1]
//line par.y:207
		{
			newRep.SetRepRoute(yyDollar[5].token)
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:208
		{
			newRep.SetRepRoute(yyDollar[4].token)
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line par.y:213
		{
			newMount.SetMount()
			newMount = actions.Mount{}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line par.y:217
		{
			actions.ShowMountedPartitions()
		}
	case 38:
		yyDollar = yyS[yypt-6 : yypt+1]
//line par.y:222
		{
			newMount.SetMountRoute(yyDollar[5].token)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:223
		{
			newMount.SetMountName(yyDollar[4].token)
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line par.y:225
		{
			newUnmount.UnmountPartition()
			newUnmount = actions.Unmount{}
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:233
		{
			newUnmount.SetUnmount(yyDollar[2].token, yyDollar[4].token)
		}
	case 44:
		yyDollar = yyS[yypt-2 : yypt+1]
//line par.y:235
		{
			newFDisk.CreatePartition()
			newPartition = actions.Partition{}
			newFDisk = actions.FDISK{}
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:245
		{
			newFDisk.SetFUnit(yyDollar[4].token)
		}
	case 48:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:246
		{
			newFDisk.SetPartitionType(yyDollar[4].token)
		}
	case 49:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:247
		{
			newFDisk.SetPartitionFit(yyDollar[4].token)
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:248
		{
			newFDisk.SetDeleteOption(yyDollar[4].token)
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:249
		{
			newFDisk.SetAddOption(yyDollar[4].token)
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:250
		{
			newFDisk.SetPSize(yyDollar[4].token)
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:251
		{
			newFDisk.SetPartitionName(yyDollar[4].token)
		}
	case 54:
		yyDollar = yyS[yypt-6 : yypt+1]
//line par.y:252
		{
			newFDisk.SetPartitionRoute(yyDollar[5].token)
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:253
		{
			newFDisk.SetPartitionRoute(yyDollar[4].token)
		}
	case 56:
		yyDollar = yyS[yypt-7 : yypt+1]
//line par.y:258
		{
			actions.RemoveDisk(yyDollar[6].token)
		}
	case 57:
		yyDollar = yyS[yypt-5 : yypt+1]
//line par.y:262
		{
			yyVAL.node = Node(yyDollar[1].token)
		}
	case 58:
		yyDollar = yyS[yypt-9 : yypt+1]
//line par.y:263
		{
			yyVAL.node = Node(yyDollar[1].token)
		}
	}
	goto yystack /* stack new state and value */
}
