// Code generated by goyacc par.y. DO NOT EDIT.

//line par.y:2
package parser

import __yyfmt__ "fmt"

//line par.y:2

import (
	"MIA-P1/actions"
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"
)

var newDisk actions.Disk = actions.Disk{}
var newPartition actions.Partition = actions.Partition{}
var newFDisk actions.FDISK = actions.FDISK{}
var newMount actions.Mount = actions.Mount{}
var newUnmount actions.Unmount = actions.Unmount{}
var stringAux string = ""
var skipFound bool = false

type node struct {
	name     string
	children []node
}

func (n node) String() string {
	buf := new(bytes.Buffer)
	n.print(buf, " ")
	return buf.String()
}

func (n node) print(out io.Writer, indent string) {
	fmt.Fprintf(out, "\n%v%v", indent, n.name)
	for _, nn := range n.children {
		nn.print(out, indent+"  ")
	}
}

func Node(name string) node           { return node{name: name} }
func (n node) append(nn ...node) node { n.children = append(n.children, nn...); return n }

//line par.y:46
type yySymType struct {
	yys   int
	node  node
	token string
}

const arrow = 57346
const add = 57347
const delete = 57348
const digit = 57349
const digits = 57350
const diskName = 57351
const equals = 57352
const exec = 57353
const fit = 57354
const fdisk = 57355
const greater = 57356
const hyphen = 57357
const idn = 57358
const id = 57359
const less = 57360
const mia_file = 57361
const mount = 57362
const mount_name = 57363
const mbr = 57364
const mkfs = 57365
const mkdisk = 57366
const number = 57367
const negNumber = 57368
const name = 57369
const path = 57370
const pause = 57371
const rmdisk = 57372
const size = 57373
const tpe = 57374
const unit = 57375
const unmount = 57376
const read = 57377
const route = 57378
const quote = 57379

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"arrow",
	"add",
	"delete",
	"digit",
	"digits",
	"diskName",
	"equals",
	"exec",
	"fit",
	"fdisk",
	"greater",
	"hyphen",
	"idn",
	"id",
	"less",
	"mia_file",
	"mount",
	"mount_name",
	"mbr",
	"mkfs",
	"mkdisk",
	"number",
	"negNumber",
	"name",
	"path",
	"pause",
	"rmdisk",
	"size",
	"tpe",
	"unit",
	"unmount",
	"read",
	"route",
	"quote",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line par.y:244

// Run exported
func Run() {
	fi := bufio.NewReader(os.NewFile(0, "stdin"))
	yyDebug = 0
	yyErrorVerbose = true
	for {
		var eqn string
		var ok bool

		fmt.Printf(">> ")
		if eqn, ok = input(fi); ok {
			l := newLexer(bytes.NewBufferString(eqn), os.Stdout, "file.name")
			yyParse(l)
		} else {
			break
		}
	}

}

// RunExec exported
func RunExec(reader *bufio.Reader) {
	yyDebug = 0
	yyErrorVerbose = true
	var stringAux string = ""

	for {
		var ok bool
		var eqn string

		if eqn, ok = input(reader); ok {
			eqn = strings.TrimSpace(eqn)
			eqn = strings.Replace(eqn, " ", "", -1)
			if strings.HasPrefix(eqn, "#") {
				continue
			}
			if len(eqn) == 0 || len(eqn) == 1 {
				continue
			}
			if skipFound == true {
				stringAux = stringAux + eqn
				stringAux = strings.Replace(stringAux, " ", "", -1)
				fmt.Println(">>", stringAux)
				l := newLexer(bytes.NewBufferString(stringAux), os.Stdout, "file.name")
				stringAux = ""
				skipFound = false
				yyParse(l)
				continue
			}
			if strings.HasSuffix(eqn, "\\*") {
				stringAux = eqn
				stringAux = strings.TrimRight(stringAux, "\\*")
				skipFound = true
				continue
			}
			fmt.Println(">>", eqn)
			l := newLexer(bytes.NewBufferString(eqn), os.Stdout, "file.name")
			yyParse(l)

		} else {
			break
		}
	}
}

func Exec(route string) {
	re, _ := regexp.Compile(`[a-zA-Z]([a-zA-Z]|[0-9])*\.mia`)
	diskName := re.FindString(route)
	if len(diskName) == 0 {
		fmt.Println(">> No file found. Try again.")
		return
	}
	file, err := os.Open(route)
	if err != nil {
		fmt.Println(">> Couldn't read file. Try again.")
		return
	}
	defer file.Close()
	reader := bufio.NewReader(file)
	RunExec(reader)
}

func input(fi *bufio.Reader) (string, bool) {
	s, err := fi.ReadString('\n')
	if err != nil {
		return "", false
	}
	return s, true
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 115

var yyAct = [...]int{
	62, 15, 112, 18, 56, 55, 102, 101, 89, 90,
	13, 54, 111, 19, 16, 110, 109, 93, 84, 20,
	17, 107, 106, 105, 14, 21, 58, 59, 104, 87,
	57, 53, 52, 61, 48, 47, 35, 113, 46, 31,
	49, 41, 40, 65, 50, 44, 68, 27, 24, 115,
	100, 97, 74, 96, 95, 94, 92, 86, 85, 60,
	43, 103, 108, 36, 32, 28, 25, 37, 33, 29,
	45, 51, 39, 91, 42, 99, 98, 88, 114, 83,
	82, 81, 80, 79, 78, 77, 76, 75, 73, 72,
	71, 70, 69, 67, 66, 64, 63, 38, 3, 26,
	1, 22, 12, 2, 10, 34, 9, 8, 30, 7,
	6, 5, 11, 23, 4,
}

var yyPact = [...]int{
	-10, -1000, -10, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 51, 50, 54, 49, 53, 48, 52,
	-1000, 93, -1000, 51, -1000, 14, 50, -1000, 43, 17,
	49, -1000, 7, 16, 48, -1000, -1, 42, -3, -1000,
	92, 91, -1000, 90, 89, -1000, 88, 87, 86, 85,
	84, -1000, 83, 82, 81, 80, 79, 78, 77, 76,
	75, -1000, -1000, -19, 41, -1000, 40, -7, -1000, 70,
	-28, 64, 39, -20, -1000, 38, 37, 36, 34, 69,
	68, 33, -30, 45, -8, -1000, -1000, -1000, -1000, -1000,
	-13, -1000, -1000, -14, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -15, -1000, 47, -21, -22, -25, -35, 5, -1000,
	-1000, -1000, -1000, 74, 32, -1000,
}

var yyPgo = [...]int{
	0, 114, 113, 48, 112, 111, 110, 109, 108, 39,
	107, 106, 105, 36, 104, 98, 103, 102, 100, 0,
	99, 47,
}

var yyR1 = [...]int{
	0, 18, 16, 16, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 4, 17, 6, 7, 8, 8, 9,
	9, 9, 9, 9, 1, 1, 2, 2, 3, 3,
	5, 20, 20, 21, 11, 12, 12, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 10, 14, 14, 19,
}

var yyR2 = [...]int{
	0, 1, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 3, 5, 2, 1, 3, 4,
	4, 4, 6, 4, 2, 1, 1, 3, 6, 4,
	2, 1, 3, 4, 2, 1, 3, 4, 4, 4,
	4, 4, 4, 4, 6, 4, 7, 5, 9, 0,
}

var yyChk = [...]int{
	-1000, -18, -16, -15, -1, -5, -6, -7, -10, -11,
	-14, -4, -17, 20, 34, 11, 24, 30, 13, 23,
	29, 35, -15, -2, -3, 15, -20, -21, 15, 15,
	-8, -9, 15, 15, -12, -13, 15, 15, 4, -3,
	28, 27, -21, 17, 28, -9, 31, 28, 27, 33,
	28, -13, 33, 32, 12, 6, 5, 31, 27, 28,
	17, 36, -19, 4, 4, -19, 4, 4, -19, 4,
	4, 4, 4, 4, -19, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 37, 17, 17, 36, 7, 36,
	37, 9, 17, 37, 17, 17, 17, 17, 7, 7,
	17, 37, 36, 16, 36, 36, 36, 36, 15, 37,
	37, 37, 37, 32, 4, 17,
}

var yyDef = [...]int{
	0, -2, 1, 2, 4, 5, 6, 7, 8, 9,
	10, 11, 12, 25, 0, 0, 0, 0, 0, 0,
	13, 0, 3, 24, 26, 0, 30, 31, 0, 0,
	16, 17, 0, 0, 34, 35, 0, 0, 0, 49,
	0, 0, 49, 0, 0, 49, 0, 0, 0, 0,
	0, 49, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 14, 27, 0, 0, 32, 0, 0, 18, 0,
	0, 0, 0, 0, 36, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 29, 33, 15, 19, 20,
	0, 21, 23, 0, 37, 38, 39, 40, 41, 42,
	43, 0, 45, 47, 0, 0, 0, 0, 0, 28,
	22, 46, 44, 0, 0, 48,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line par.y:165
		{
			actions.PauseAction()
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line par.y:167
		{
			actions.ReadFile(yyDollar[3].token)
		}
	case 15:
		yyDollar = yyS[yypt-5 : yypt+1]
//line par.y:169
		{
			Exec(yyDollar[5].token)
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line par.y:171
		{
			newDisk.CreateDisk()
			newDisk = actions.Disk{}
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:179
		{
			newDisk.SetDiskSize(yyDollar[4].token)
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:180
		{
			newDisk.SetDiskRoute(yyDollar[4].token)
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:181
		{
			newDisk.SetDiskName(yyDollar[4].token)
		}
	case 22:
		yyDollar = yyS[yypt-6 : yypt+1]
//line par.y:182
		{
			newDisk.SetDiskRoute(yyDollar[5].token)
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:183
		{
			newDisk.SetDiskUnit(yyDollar[4].token)
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line par.y:188
		{
			newMount.SetMount()
			newMount = actions.Mount{}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line par.y:192
		{
			actions.ShowMountedPartitions()
		}
	case 28:
		yyDollar = yyS[yypt-6 : yypt+1]
//line par.y:197
		{
			newMount.SetMountRoute(yyDollar[5].token)
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:198
		{
			newMount.SetMountName(yyDollar[4].token)
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line par.y:200
		{
			newUnmount.UnmountPartition()
			newUnmount = actions.Unmount{}
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:208
		{
			newUnmount.SetUnmount(yyDollar[2].token, yyDollar[4].token)
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line par.y:210
		{
			newFDisk.CreatePartition()
			newPartition = actions.Partition{}
			newFDisk = actions.FDISK{}
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:220
		{
			newFDisk.SetFUnit(yyDollar[4].token)
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:221
		{
			newFDisk.SetPartitionType(yyDollar[4].token)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:222
		{
			newFDisk.SetPartitionFit(yyDollar[4].token)
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:223
		{
			newFDisk.SetDeleteOption(yyDollar[4].token)
		}
	case 41:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:224
		{
			newFDisk.SetAddOption(yyDollar[4].token)
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:225
		{
			newFDisk.SetPSize(yyDollar[4].token)
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:226
		{
			newFDisk.SetPartitionName(yyDollar[4].token)
		}
	case 44:
		yyDollar = yyS[yypt-6 : yypt+1]
//line par.y:227
		{
			newFDisk.SetPartitionRoute(yyDollar[5].token)
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line par.y:228
		{
			newFDisk.SetPartitionRoute(yyDollar[4].token)
		}
	case 46:
		yyDollar = yyS[yypt-7 : yypt+1]
//line par.y:233
		{
			actions.RemoveDisk(yyDollar[6].token)
		}
	case 47:
		yyDollar = yyS[yypt-5 : yypt+1]
//line par.y:237
		{
			yyVAL.node = Node(yyDollar[1].token)
		}
	case 48:
		yyDollar = yyS[yypt-9 : yypt+1]
//line par.y:238
		{
			yyVAL.node = Node(yyDollar[1].token)
		}
	}
	goto yystack /* stack new state and value */
}
